---
name: lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "."



